name: build production

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            swistakcodes/blog:latest
            swistakcodes/blog:${{ github.sha }}
          build-args: |
            HIDE=true
            URL=https://swistak.codes
            MATOMO_URL=https://radioactive-toy.swistak.codes
            MATOMO_ID=1
            PUBLIC_SEARCH_HOST=dont-hate-me.swistak.codes
            PUBLIC_SEARCH_PORT=443
            PUBLIC_SEARCH_PROTOCOL=https

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Restart container on server
        run: ssh staging './start.sh blog'
