name: Sync to Public Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone public repository
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${PUBLIC_REPO_TOKEN}@github.com/swistak-codes/blog.git public-repo
          cd public-repo
          git checkout main || git checkout -b main

      - name: Copy files to public repository
        run: |
          rsync -a --exclude='.git' --exclude='public-repo' . public-repo/

      - name: Create new commits
        run: |
          cd public-repo
          git add .
          git diff --staged --quiet || git commit -m "Update $(date +'%Y-%m-%d')"

      - name: Push to public repository
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          cd public-repo
          git push origin main
